
from txamqpprovisioner.pychangelogger_parser import PyChangeloggerMessageParserFactory
pcl_parser_factory = PyChangeloggerMessageParserFactory()


from txamqpprovisioner.subject_parser import SubjectMessageParserFactory
subject_parser_factory = SubjectMessageParserFactory()

from txamqpprovisioner.basic_full_sync_parser import BasicFullSyncMessageParserFactory
basic_full_sync_parser_factory = BasicFullSyncMessageParserFactory()

