
from txamqpprovisioner.ldap_provisioner import LDAPProvisionerFactory
ldap_provisioner_factory = LDAPProvisionerFactory()

from txamqpprovisioner.kiki import KikiProvisionerFactory
kiki_provisioner_factory = KikiProvisionerFactory()

from txamqpprovisioner.ssh_provisioner import SSHProvisionerFactory
ssh_provisioner_factory = SSHProvisionerFactory()

from txamqpprovisioner.board_effect_provisioner import BoardEffectProvisionerFactory
board_effect_provisioner_factory = BoardEffectProvisionerFactory()

from txamqpprovisioner.slack_provisioner import SlackProvisionerFactory
slack_provisioner_factory = SlackProvisionerFactory()

from txamqpprovisioner.o365_provisioner import O365ProvisionerFactory
o365_provisioner_factory = O365ProvisionerFactory()

from txamqpprovisioner.moodle_provisioner import MoodleProvisionerFactory
moodle_provisioner_factory = MoodleProvisionerFactory()

from txamqpprovisioner.qualtrics_provisioner import QualtricsProvisionerFactory
qualtrics_provisioner_factory = QualtricsProvisionerFactory()

from txamqpprovisioner.duo_provisioner import DuoSecurityProvisionerFactory
duo_provisioner_factory = DuoSecurityProvisionerFactory()

from txamqpprovisioner.zoom_provisioner import ZoomProvisionerFactory
zoom_provisioner_factory = ZoomProvisionerFactory()

from txamqpprovisioner.ad_account_provisioner import ADAccountProvisionerFactory
ad_account_provisioner_factory = ADAccountProvisionerFactory()
